#ifndef CONSTANTS_H
#define CONSTANTS_H

namespace audio_app {

enum Command {
	COMMAND_NOTINITIALIZED,
	COMMAND_PLAY,
	COMMAND_PAUSE,
	COMMAND_STOP,
	COMMAND_QUIT,
	COMMAND_UNEXPECTEDUSERINPUT,
	COMMAND_ERROR,
	COMMAND_CANNOTRECEIVEDATA
};

enum ProcessStatus {
	PROCESSSTATUS_NOTINITIALIZED,
	PROCESSSTATUS_SUCCESS,
	PROCESSSTATUS_FAILED,
	PROCESSSTATUS_PROCESSING,
	PROCESSSTATUS_QUIT,
	PROCESSSTATUS_ERROR
};

enum FileLoadStatus {
	FILELOADSTATUS_NOTINITIALIZED,
	FILELOADSTATUS_SUCCESSFULLYLOADED,
	FILELOADSTATUS_SUCCESSFULLYUNLOADED,
	FILELOADSTATUS_NOTLOADED,
	FILELOADSTATUS_ERROR,
};

enum InstanceType {
	INSTANCE_NOTINITIALIZED,
	INSTANCE_MUSIC,
	INSTANCE_AUDIOCONTROLLER,
	INSTANCE_AUDIOMODEL,
	INSTANCE_USERINPUT,
	INSTANCE_LOGGER,
	INSTANCE_ERROR
};
enum ServerStatus {
	SERVER_NOTINITIATED,
	SERVER_STARTED,
	SERVER_STOPPED,
	SERVER_ERROR,
	SERVER_ERRORPORTBINDING,
	SERVER_ERRORCLIENTCONNECTION
};
}
#endif
